FROM python:3.9-slim-buster

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt

WORKDIR /app
COPY producer_fx_mock.py /app/

CMD [ "python", "./producer_fx_mock.py" ]